
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Jul 22 2019 17:12:54 BRT (Jul 22 2019 20:12:54 UTC)

// Verification Directory fv/sanduba 

module sanduba(M100, R_bacon, R_atum, R_green, clock, reset, dev, D100,
     Bacon, Atum, Green, Busy);
  input M100, R_bacon, R_atum, R_green, clock, reset, dev;
  output D100, Bacon, Atum, Green, Busy;
  wire M100, R_bacon, R_atum, R_green, clock, reset, dev;
  wire D100, Bacon, Atum, Green, Busy;
  wire [4:0] count;
  wire [2:0] EA;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_13, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_50, n_51;
  wire n_52, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71;
  C12T28SOI_LR_SDFPRQX8_P0 \count_reg[4] (.RN (n_71), .CP (clock), .D
       (n_69), .TI (n_67), .TE (count[4]), .Q (count[4]));
  C12T28SOI_LR_DFPRQX17_P0 \count_reg[3] (.RN (n_71), .CP (clock), .D
       (n_70), .Q (count[3]));
  C12T28SOI_LR_OAI12X6_P0 g1816(.A (n_68), .B (n_66), .C (n_55), .Z
       (n_70));
  C12T28SOI_LR_OAI22X5_P0 g1819(.A (n_68), .B (n_63), .C (n_47), .D
       (n_34), .Z (n_69));
  C12T28SOI_LR_OAI211X5_P0 g1821(.A (n_68), .B (n_65), .C (n_18), .D
       (n_44), .Z (n_67));
  C12T28SOI_LR_DFPRQNX17_P0 \count_reg[2] (.RN (n_71), .CP (clock), .D
       (n_64), .QN (count[2]));
  C12T28SOI_LR_CBI4I6X5_P0 g1818(.A (n_62), .B (n_61), .C (count[3]),
       .D (n_65), .Z (n_66));
  C12T28SOI_LR_OAI12X6_P0 g1820(.A (n_68), .B (n_60), .C (n_41), .Z
       (n_64));
  C12T28SOI_LR_IVX8_P0 g1823(.A (n_65), .Z (n_63));
  C12T28SOI_LR_DFPRQNX17_P0 \count_reg[1] (.RN (n_71), .CP (clock), .D
       (n_59), .QN (count[1]));
  C12T28SOI_LR_NOR3X6_P0 g1824(.A (count[3]), .B (n_62), .C (n_61), .Z
       (n_65));
  C12T28SOI_LR_DFPRQNX17_P0 \EA_reg[1] (.RN (n_71), .CP (clock), .D
       (n_58), .QN (EA[1]));
  C12T28SOI_LRS_XNOR2X6_P0 g1826(.A (n_20), .B (n_56), .Z (n_60));
  C12T28SOI_LR_AO222X8_P0 g1825(.A (n_40), .B (n_11), .C (n_51), .D
       (n_35), .E (n_50), .F (n_57), .Z (n_59));
  C12T28SOI_LR_DFPRQNX17_P0 \EA_reg[0] (.RN (n_71), .CP (clock), .D
       (n_54), .QN (EA[0]));
  C12T28SOI_LR_DFPRQNX17_P0 \count_reg[0] (.RN (n_71), .CP (clock), .D
       (n_48), .QN (count[0]));
  C12T28SOI_LR_DFPRQNX17_P0 \EA_reg[2] (.RN (n_71), .CP (clock), .D
       (n_46), .QN (EA[2]));
  C12T28SOI_LR_OAI222X3_P0 g1833(.A (EA[1]), .B (n_52), .C (n_45), .D
       (n_42), .E (n_57), .F (n_8), .Z (n_58));
  C12T28SOI_LR_AND2X8_P0 g1830(.A (n_19), .B (n_56), .Z (n_61));
  C12T28SOI_LR_AOI22X4_P0 g1829(.A (count[3]), .B (n_43), .C (n_17), .D
       (n_39), .Z (n_55));
  C12T28SOI_LR_OAI22X5_P0 g1834(.A (n_37), .B (Busy), .C (n_5), .D
       (n_52), .Z (n_54));
  C12T28SOI_LR_FA1X8_P0 g1831(.A0 (n_50), .B0 (D100), .CI (n_23), .CO
       (n_56), .S0 (n_51));
  C12T28SOI_LR_OAI222X3_P0 g1838(.A (n_31), .B (n_68), .C (n_30), .D
       (n_47), .E (count[0]), .F (n_38), .Z (n_48));
  C12T28SOI_LR_AOI13X5_P0 g1842(.A (n_36), .B (n_32), .C (n_28), .D
       (n_45), .Z (n_46));
  C12T28SOI_LR_IVX8_P0 g1835(.A (n_43), .Z (n_44));
  C12T28SOI_LR_AOI13X5_P0 g1841(.A (R_atum), .B (n_7), .C (n_22), .D
       (n_33), .Z (n_42));
  C12T28SOI_LR_AOI22X4_P0 g1839(.A (n_40), .B (n_26), .C (n_25), .D
       (n_57), .Z (n_41));
  C12T28SOI_LR_OAI21X5_P0 g1836(.A (n_47), .B (n_39), .C (n_38), .Z
       (n_43));
  C12T28SOI_LR_AOI12X6_P0 g1843(.A (n_36), .B (n_27), .C (M100), .Z
       (n_37));
  C12T28SOI_LR_IVX8_P0 g1846(.A (n_68), .Z (n_35));
  C12T28SOI_LR_NAND2X7_P0 g1840(.A (count[3]), .B (n_39), .Z (n_34));
  C12T28SOI_LR_AOI21X6_P0 g1845(.A (n_6), .B (n_32), .C (n_21), .Z
       (n_33));
  C12T28SOI_LR_AOI21X6_P0 g1850(.A (n_30), .B (n_29), .C (n_24), .Z
       (n_31));
  C12T28SOI_LR_AO22X8_P0 g1847(.A (n_29), .B (n_10), .C (n_52), .D
       (n_2), .Z (n_68));
  C12T28SOI_LR_IVX8_P0 g1848(.A (n_27), .Z (n_28));
  C12T28SOI_LR_HA1X8_P0 g1844(.A0 (n_15), .B0 (n_25), .CO (n_39), .S0
       (n_26));
  C12T28SOI_LR_IVX8_P0 g1851(.A (n_23), .Z (n_24));
  C12T28SOI_LR_NOR2AX6_P0 g1849(.A (R_atum), .B (n_22), .Z (n_27));
  C12T28SOI_LR_OAI211X5_P0 g1855(.A (dev), .B (R_green), .C (n_1), .D
       (n_36), .Z (n_21));
  C12T28SOI_LR_NOR2AX6_P0 g1856(.A (n_19), .B (n_62), .Z (n_20));
  C12T28SOI_LR_OR2X8_P0 g1854(.A (n_30), .B (n_29), .Z (n_23));
  C12T28SOI_LR_NOR2X7_P0 g1853(.A (n_30), .B (n_16), .Z (n_52));
  C12T28SOI_LR_IVX8_P0 g1858(.A (n_17), .Z (n_18));
  C12T28SOI_LR_NAND2X7_P0 g1857(.A (R_green), .B (n_16), .Z (n_32));
  C12T28SOI_LR_NOR2AX6_P0 g1852(.A (n_13), .B (n_15), .Z (n_22));
  C12T28SOI_LR_NOR2X7_P0 g1860(.A (count[3]), .B (n_47), .Z (n_17));
  C12T28SOI_LR_NAND2X7_P0 g1861(.A (count[2]), .B (Bacon), .Z (n_19));
  C12T28SOI_LR_NOR2X7_P0 g1865(.A (count[2]), .B (Bacon), .Z (n_62));
  C12T28SOI_LR_IVX8_P0 g1867(.A (n_47), .Z (n_40));
  C12T28SOI_LR_NAND2AX7_P0 g1862(.A (n_13), .B (R_bacon), .Z (n_36));
  C12T28SOI_LR_OR2X8_P0 g1863(.A (M100), .B (Busy), .Z (n_45));
  C12T28SOI_LR_NAND2X7_P0 g1864(.A (count[1]), .B (n_13), .Z (n_16));
  C12T28SOI_LR_NOR2X7_P0 g1866(.A (Atum), .B (D100), .Z (n_29));
  C12T28SOI_LR_HA1X8_P0 g1859(.A0 (n_50), .B0 (n_30), .CO (n_15), .S0
       (n_11));
  C12T28SOI_LR_NOR2X7_P0 g1870(.A (n_4), .B (n_10), .Z (Bacon));
  C12T28SOI_LR_NOR2X3_P0 g1868(.A (EA[1]), .B (n_10), .Z (Green));
  C12T28SOI_LR_NAND2AX7_P0 g1871(.A (EA[0]), .B (n_8), .Z (n_47));
  C12T28SOI_LR_NAND2AX3_P0 g1872(.A (R_green), .B (n_6), .Z (n_7));
  C12T28SOI_LR_NAND2X7_P0 g1873(.A (n_4), .B (n_57), .Z (n_5));
  C12T28SOI_LR_NAND2X7_P0 g1869(.A (EA[1]), .B (n_57), .Z (Busy));
  C12T28SOI_LR_NOR3X6_P0 g1874(.A (EA[2]), .B (n_4), .C (EA[0]), .Z
       (Atum));
  C12T28SOI_LR_AND3X8_P0 g1876(.A (n_0), .B (EA[2]), .C (n_4), .Z
       (D100));
  C12T28SOI_LR_NOR3X6_P0 g1875(.A (count[4]), .B (count[3]), .C (n_25),
       .Z (n_13));
  C12T28SOI_LR_NAND2X7_P0 g1878(.A (n_3), .B (EA[0]), .Z (n_10));
  C12T28SOI_LR_NOR2X7_P0 g1881(.A (n_3), .B (n_4), .Z (n_8));
  C12T28SOI_LR_IVX8_P0 g1879(.A (n_57), .Z (n_38));
  C12T28SOI_LR_NOR2X7_P0 g1877(.A (EA[0]), .B (EA[1]), .Z (n_2));
  C12T28SOI_LR_NOR2X3_P0 g1880(.A (dev), .B (R_bacon), .Z (n_6));
  C12T28SOI_LR_AND2X8_P0 g1882(.A (EA[2]), .B (EA[0]), .Z (n_57));
  C12T28SOI_LR_IVX8_P0 g1887(.A (EA[2]), .Z (n_3));
  C12T28SOI_LR_IVX8_P0 g1884(.A (count[0]), .Z (n_30));
  C12T28SOI_LR_IVX8_P0 g1885(.A (EA[1]), .Z (n_4));
  C12T28SOI_LR_IVX4_P0 g1890(.A (reset), .Z (n_71));
  C12T28SOI_LR_IVX4_P0 g1886(.A (R_atum), .Z (n_1));
  C12T28SOI_LR_IVX8_P0 g1883(.A (EA[0]), .Z (n_0));
  C12T28SOI_LR_IVX8_P0 g1889(.A (count[1]), .Z (n_50));
  C12T28SOI_LR_IVX8_P0 g1888(.A (count[2]), .Z (n_25));
endmodule

