
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Jul 26 2019 17:51:39 -03 (Jul 26 2019 20:51:39 UTC)

// Verification Directory fv/sanduba 

module sanduba(clock, reset, M100, DEV, R_green, R_atum, R_bacon, busy,
     D100, GREEN, ATUM, BACON);
  input clock, reset, M100, DEV, R_green, R_atum, R_bacon;
  output busy, D100, GREEN, ATUM, BACON;
  wire clock, reset, M100, DEV, R_green, R_atum, R_bacon;
  wire busy, D100, GREEN, ATUM, BACON;
  wire [4:0] grana;
  wire [2:0] EA;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_14, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63;
  C12T28SOI_LR_DFPRQX17_P0 \grana_reg[3] (.RN (n_63), .CP (clock), .D
       (n_62), .Q (grana[3]));
  C12T28SOI_LR_DFPRQX17_P0 \grana_reg[4] (.RN (n_63), .CP (clock), .D
       (n_60), .Q (grana[4]));
  C12T28SOI_LR_DFPRQNX17_P0 \grana_reg[2] (.RN (n_63), .CP (clock), .D
       (n_61), .QN (grana[2]));
  C12T28SOI_LR_AO222X8_P0 g2275(.A (n_37), .B (n_59), .C (grana[3]), .D
       (n_52), .E (n_26), .F (n_17), .Z (n_62));
  C12T28SOI_LRS_XNOR2X6_P0 g2280(.A (grana[2]), .B (n_57), .Z (n_61));
  C12T28SOI_LR_AO212X8_P0 g2274(.A (grana[4]), .B (n_49), .C (n_23), .D
       (n_59), .E (n_19), .Z (n_60));
  C12T28SOI_LR_DFPRQNX17_P0 \grana_reg[1] (.RN (n_63), .CP (clock), .D
       (n_58), .QN (grana[1]));
  C12T28SOI_LR_DFPRQX17_P0 \EA_reg[1] (.RN (n_63), .CP (clock), .D
       (n_55), .Q (EA[1]));
  C12T28SOI_LR_DFPRQNX17_P0 \EA_reg[2] (.RN (n_63), .CP (clock), .D
       (n_56), .QN (EA[2]));
  C12T28SOI_LRS_XOR2X6_P0 g2279(.A (grana[1]), .B (n_44), .Z (n_58));
  C12T28SOI_LR_OA112X8_P0 g2290(.A (n_12), .B (n_47), .C (n_53), .D
       (n_50), .Z (n_57));
  C12T28SOI_LR_OAI211X5_P0 g2282(.A (n_41), .B (n_8), .C (n_51), .D
       (n_54), .Z (n_56));
  C12T28SOI_LR_DFPRQNX17_P0 \EA_reg[0] (.RN (n_63), .CP (clock), .D
       (n_45), .QN (EA[0]));
  C12T28SOI_LR_CBI4I6X5_P0 g2277(.A (n_3), .B (n_35), .C (n_54), .D
       (n_53), .Z (n_55));
  C12T28SOI_LR_OAI211X5_P0 g2288(.A (grana[2]), .B (n_51), .C (n_36),
       .D (n_50), .Z (n_52));
  C12T28SOI_LR_DFPRQX17_P0 \grana_reg[0] (.RN (n_63), .CP (clock), .D
       (n_48), .Q (grana[0]));
  C12T28SOI_LR_NAND2X7_P0 g2284(.A (n_38), .B (n_50), .Z (n_49));
  C12T28SOI_LR_OAI222X3_P0 g2285(.A (n_30), .B (n_43), .C (n_42), .D
       (n_33), .E (grana[0]), .F (n_47), .Z (n_48));
  C12T28SOI_LR_AO12X8_P0 g2286(.A (n_25), .B (n_40), .C (BACON), .Z
       (n_59));
  C12T28SOI_LR_AO112X8_P0 g2287(.A (n_34), .B (EA[0]), .C (EA[1]), .D
       (n_10), .Z (n_45));
  C12T28SOI_LR_OA22X8_P0 g2289(.A (n_31), .B (n_43), .C (n_42), .D
       (n_47), .Z (n_44));
  C12T28SOI_LR_AOI112X5_P0 g2294(.A (n_28), .B (n_11), .C (DEV), .D
       (n_21), .Z (n_41));
  C12T28SOI_LR_OR2X8_P0 g2292(.A (n_43), .B (n_40), .Z (n_50));
  C12T28SOI_LR_NOR3X6_P0 g2291(.A (EA[1]), .B (EA[0]), .C (n_54), .Z
       (D100));
  C12T28SOI_LR_OA112X8_P0 g2297(.A (n_37), .B (n_51), .C (n_18), .D
       (n_36), .Z (n_38));
  C12T28SOI_LR_AOI22X4_P0 g2293(.A (n_2), .B (n_20), .C (R_bacon), .D
       (n_27), .Z (n_35));
  C12T28SOI_LR_AO112X8_P0 g2295(.A (R_bacon), .B (n_22), .C (n_4), .D
       (n_14), .Z (n_34));
  C12T28SOI_LR_NOR3AX6_P0 g2296(.A (n_53), .B (BACON), .C (GREEN), .Z
       (n_33));
  C12T28SOI_LRS_XOR2X6_P0 g2298(.A (n_29), .B (n_30), .Z (n_31));
  C12T28SOI_LR_PAO2X8_P0 g2299(.A (n_29), .B (grana[1]), .P (n_16), .Z
       (n_40));
  C12T28SOI_LR_IVX8_P0 g2300(.A (n_27), .Z (n_28));
  C12T28SOI_LR_OA12X8_P0 g2308(.A (n_47), .B (n_26), .C (n_53), .Z
       (n_36));
  C12T28SOI_LR_IVX8_P0 g2301(.A (n_24), .Z (n_54));
  C12T28SOI_LR_IVX8_P0 g2302(.A (n_43), .Z (n_25));
  C12T28SOI_LR_AOI13X5_P0 g2304(.A (grana[1]), .B (n_42), .C (n_23), .D
       (EA[2]), .Z (n_24));
  C12T28SOI_LR_NOR2X7_P0 g2303(.A (R_atum), .B (n_22), .Z (n_27));
  C12T28SOI_LR_NOR3AX6_P0 g2306(.A (R_atum), .B (n_20), .C (M100), .Z
       (n_21));
  C12T28SOI_LR_NOR4ABX6_P0 g2307(.A (grana[3]), .B (n_26), .C
       (grana[4]), .D (n_47), .Z (n_19));
  C12T28SOI_LR_IVX8_P0 g2313(.A (n_17), .Z (n_18));
  C12T28SOI_LR_IVX8_P0 g2309(.A (n_16), .Z (n_30));
  C12T28SOI_LR_NOR3X6_P0 g2305(.A (GREEN), .B (n_9), .C (ATUM), .Z
       (n_43));
  C12T28SOI_LR_AND3X8_P0 g2314(.A (R_green), .B (grana[1]), .C (n_23),
       .Z (n_14));
  C12T28SOI_LR_NOR2X7_P0 g2316(.A (grana[3]), .B (n_47), .Z (n_17));
  C12T28SOI_LR_OA12X8_P0 g2317(.A (EA[2]), .B (EA[0]), .C (busy), .Z
       (n_53));
  C12T28SOI_LR_OR2X8_P0 g2310(.A (R_green), .B (n_23), .Z (n_22));
  C12T28SOI_LR_NAND2AX7_P0 g2311(.A (n_12), .B (n_23), .Z (n_20));
  C12T28SOI_LR_PAO2X8_P0 g2315(.A (R_green), .B (R_bacon), .P (n_1), .Z
       (n_11));
  C12T28SOI_LR_NOR2X7_P0 g2312(.A (grana[0]), .B (GREEN), .Z (n_16));
  C12T28SOI_LR_NOR2AX6_P0 g2326(.A (n_6), .B (n_10), .Z (n_51));
  C12T28SOI_LR_NOR2AX6_P0 g2327(.A (n_12), .B (grana[2]), .Z (n_26));
  C12T28SOI_LR_NAND2X7_P0 g2320(.A (EA[0]), .B (n_7), .Z (busy));
  C12T28SOI_LR_IVX8_P0 g2323(.A (n_9), .Z (n_29));
  C12T28SOI_LR_NAND2X7_P0 g2322(.A (n_8), .B (n_7), .Z (n_47));
  C12T28SOI_LR_AND3X8_P0 g2329(.A (EA[1]), .B (n_5), .C (EA[0]), .Z
       (n_9));
  C12T28SOI_LR_NOR2X7_P0 g2325(.A (n_8), .B (n_6), .Z (BACON));
  C12T28SOI_LR_AND3X8_P0 g2328(.A (n_5), .B (n_0), .C (EA[0]), .Z
       (GREEN));
  C12T28SOI_LR_OR2X8_P0 g2318(.A (R_atum), .B (n_3), .Z (n_4));
  C12T28SOI_LR_NOR2X7_P0 g2319(.A (EA[0]), .B (n_6), .Z (ATUM));
  C12T28SOI_LR_NOR2AX6_P0 g2321(.A (n_37), .B (grana[4]), .Z (n_23));
  C12T28SOI_LR_NOR3AX6_P0 g2324(.A (R_atum), .B (R_green), .C
       (R_bacon), .Z (n_2));
  C12T28SOI_LR_NOR2X7_P0 g2331(.A (EA[2]), .B (n_8), .Z (n_10));
  C12T28SOI_LR_NOR2X7_P0 g2334(.A (EA[1]), .B (n_5), .Z (n_7));
  C12T28SOI_LR_NOR2X7_P0 g2335(.A (grana[1]), .B (n_42), .Z (n_12));
  C12T28SOI_LR_NAND2AX3_P0 g2330(.A (R_atum), .B (M100), .Z (n_1));
  C12T28SOI_LR_OR2X8_P0 g2333(.A (DEV), .B (M100), .Z (n_3));
  C12T28SOI_LR_NAND2X7_P0 g2332(.A (EA[1]), .B (EA[2]), .Z (n_6));
  C12T28SOI_LR_NOR2AX6_P0 g2336(.A (grana[2]), .B (grana[3]), .Z
       (n_37));
  C12T28SOI_LR_IVX8_P0 g2339(.A (EA[0]), .Z (n_8));
  C12T28SOI_LR_IVX8_P0 g2341(.A (grana[0]), .Z (n_42));
  C12T28SOI_LR_IVX8_P0 g2340(.A (EA[1]), .Z (n_0));
  C12T28SOI_LR_IVX8_P0 g2337(.A (EA[2]), .Z (n_5));
  C12T28SOI_LR_IVX4_P0 g2338(.A (reset), .Z (n_63));
endmodule

