
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Jul 22 2019 16:58:40 BRT (Jul 22 2019 19:58:40 UTC)

// Verification Directory fv/sanduba 

module sanduba(clock, reset, M100, DEV, R_bacon, R_atum, R_green, busy,
     D100, BACON, ATUM, GREEN);
  input clock, reset, M100, DEV, R_bacon, R_atum, R_green;
  output busy, D100, BACON, ATUM, GREEN;
  wire clock, reset, M100, DEV, R_bacon, R_atum, R_green;
  wire busy, D100, BACON, ATUM, GREEN;
  wire [4:0] credito;
  wire [2:0] PE;
  wire [2:0] EA;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_33;
  wire n_34, n_35, n_36, n_37, n_39, n_40, n_41, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  C12T28SOI_LR_DFPRQX17_P0 \credito_reg[4] (.RN (n_76), .CP (clock), .D
       (n_75), .Q (credito[4]));
  C12T28SOI_LR_DFPRQX17_P0 \credito_reg[3] (.RN (n_76), .CP (clock), .D
       (n_74), .Q (credito[3]));
  C12T28SOI_LR_AO112X8_P0 g2764(.A (n_15), .B (n_73), .C (n_46), .D
       (n_72), .Z (n_75));
  C12T28SOI_LR_AO212X8_P0 g2765(.A (n_58), .B (n_73), .C (n_44), .D
       (n_45), .E (n_70), .Z (n_74));
  C12T28SOI_LR_DFPRQNX17_P0 \EA_reg[1] (.RN (n_76), .CP (clock), .D
       (PE[1]), .QN (EA[1]));
  C12T28SOI_LR_DFPRQX17_P0 \EA_reg[2] (.RN (n_76), .CP (clock), .D
       (PE[2]), .Q (EA[2]));
  C12T28SOI_LR_DFPRQNX17_P0 \EA_reg[0] (.RN (n_76), .CP (clock), .D
       (PE[0]), .QN (EA[0]));
  C12T28SOI_LR_OA12X8_P0 g2772(.A (n_59), .B (n_69), .C (credito[4]),
       .Z (n_72));
  C12T28SOI_LR_LDLQX8_P0 \PE_reg[0] (.GN (n_71), .D (n_64), .Q (PE[0]));
  C12T28SOI_LR_LDLQX8_P0 \PE_reg[1] (.GN (n_71), .D (n_65), .Q (PE[1]));
  C12T28SOI_LR_LDLQX8_P0 \PE_reg[2] (.GN (n_71), .D (n_39), .Q (PE[2]));
  C12T28SOI_LR_CB4I1X8_P0 g2771(.A (credito[2]), .B (n_61), .C (n_69),
       .D (credito[3]), .Z (n_70));
  C12T28SOI_LR_SDFPRQX8_P0 \credito_reg[2] (.RN (n_76), .CP (clock), .D
       (credito[2]), .TI (n_1), .TE (n_68), .Q (credito[2]));
  C12T28SOI_LR_NOR4ABX6_P0 g2773(.A (n_62), .B (EA[0]), .C (M100), .D
       (DEV), .Z (n_71));
  C12T28SOI_LR_DFPRQNX17_P0 \credito_reg[1] (.RN (n_76), .CP (clock),
       .D (n_67), .QN (credito[1]));
  C12T28SOI_LR_OAI12X6_P0 g2775(.A (credito[2]), .B (n_66), .C (n_68),
       .Z (n_69));
  C12T28SOI_LR_OAI222X3_P0 g2777(.A (credito[1]), .B (n_47), .C (n_63),
       .D (n_57), .E (n_66), .F (n_12), .Z (n_67));
  C12T28SOI_LR_AOI22X4_P0 g2780(.A (n_56), .B (n_8), .C (n_24), .D
       (n_52), .Z (n_65));
  C12T28SOI_LR_AO22X8_P0 g2781(.A (EA[0]), .B (n_55), .C (n_13), .D
       (M100), .Z (n_64));
  C12T28SOI_LR_OAI12X6_P0 g2776(.A (n_63), .B (n_60), .C (n_26), .Z
       (n_73));
  C12T28SOI_LR_NOR4ABX6_P0 g2779(.A (n_27), .B (n_49), .C (n_53), .D
       (n_61), .Z (n_62));
  C12T28SOI_LR_AOI12X6_P0 g2778(.A (n_41), .B (n_60), .C (n_31), .Z
       (n_68));
  C12T28SOI_LR_DFPRQNX17_P0 \credito_reg[0] (.RN (n_76), .CP (clock),
       .D (n_48), .QN (credito[0]));
  C12T28SOI_LR_OAI22X5_P0 g2790(.A (n_58), .B (n_43), .C (credito[3]),
       .D (n_66), .Z (n_59));
  C12T28SOI_LR_IVX8_P0 g2782(.A (n_51), .Z (n_57));
  C12T28SOI_LR_AO112X8_P0 g2785(.A (n_28), .B (n_20), .C (M100), .D
       (n_54), .Z (n_56));
  C12T28SOI_LR_AO22X8_P0 g2786(.A (n_11), .B (n_54), .C (n_36), .D
       (n_53), .Z (n_55));
  C12T28SOI_LR_AOI21X6_P0 g2787(.A (EA[0]), .B (n_37), .C (n_2), .Z
       (n_52));
  C12T28SOI_LR_FA1X8_P0 g2783(.A0 (n_9), .B0 (D100), .CI (n_18), .CO
       (n_60), .S0 (n_51));
  C12T28SOI_LR_AOI211X4_P0 g2788(.A (R_bacon), .B (n_7), .C (n_40), .D
       (n_35), .Z (n_49));
  C12T28SOI_LR_OAI222X3_P0 g2789(.A (credito[0]), .B (n_47), .C (n_63),
       .D (n_34), .E (n_33), .F (n_66), .Z (n_48));
  C12T28SOI_LR_NOR3AX6_P0 g2793(.A (n_45), .B (n_44), .C (credito[4]),
       .Z (n_46));
  C12T28SOI_LR_IVX8_P0 g2794(.A (n_43), .Z (n_61));
  C12T28SOI_LR_NOR2X7_P0 g2797(.A (BACON), .B (n_41), .Z (n_43));
  C12T28SOI_LR_AND2X8_P0 g2791(.A (n_40), .B (n_21), .Z (n_54));
  C12T28SOI_LR_NOR3X6_P0 g2792(.A (M100), .B (n_22), .C (busy), .Z
       (n_39));
  C12T28SOI_LR_NAND2AX3_P0 g2795(.A (n_36), .B (n_53), .Z (n_37));
  C12T28SOI_LR_OA12X8_P0 g2798(.A (R_atum), .B (n_29), .C (R_green), .Z
       (n_35));
  C12T28SOI_LR_AND3X8_P0 g2800(.A (credito[2]), .B (n_30), .C (n_14),
       .Z (n_45));
  C12T28SOI_LR_AOI21X6_P0 g2805(.A (n_33), .B (GREEN), .C (n_19), .Z
       (n_34));
  C12T28SOI_LR_IVX8_P0 g2803(.A (n_63), .Z (n_41));
  C12T28SOI_LR_OAI12X6_P0 g2796(.A (n_30), .B (n_66), .C (n_25), .Z
       (n_31));
  C12T28SOI_LR_OR2X8_P0 g2801(.A (n_33), .B (n_29), .Z (n_36));
  C12T28SOI_LR_OA12X8_P0 g2799(.A (n_30), .B (n_23), .C (R_atum), .Z
       (n_40));
  C12T28SOI_LR_IVX4_P0 g2808(.A (n_27), .Z (n_28));
  C12T28SOI_LR_AND2X8_P0 g2802(.A (n_26), .B (n_25), .Z (n_47));
  C12T28SOI_LR_AND2X8_P0 g2806(.A (n_24), .B (n_17), .Z (n_63));
  C12T28SOI_LR_NAND2X3_P0 g2811(.A (R_bacon), .B (n_23), .Z (n_27));
  C12T28SOI_LR_NOR3X6_P0 g2804(.A (n_4), .B (n_21), .C (n_20), .Z
       (n_22));
  C12T28SOI_LR_IVX8_P0 g2809(.A (n_18), .Z (n_19));
  C12T28SOI_LR_NOR2X7_P0 g2813(.A (ATUM), .B (GREEN), .Z (n_17));
  C12T28SOI_LR_OR2X8_P0 g2812(.A (n_33), .B (GREEN), .Z (n_18));
  C12T28SOI_LR_NAND2X3_P0 g2814(.A (credito[1]), .B (n_15), .Z (n_29));
  C12T28SOI_LR_IVX8_P0 g2817(.A (n_66), .Z (n_14));
  C12T28SOI_LR_IVX4_P0 g2816(.A (busy), .Z (n_13));
  C12T28SOI_LR_IVX8_P0 g2807(.A (n_10), .Z (n_12));
  C12T28SOI_LR_MUXI21X3_P0 g2815(.D0 (n_3), .D1 (n_11), .S0 (EA[0]), .Z
       (n_25));
  C12T28SOI_LR_HA1X8_P0 g2810(.A0 (n_9), .B0 (n_33), .CO (n_30), .S0
       (n_10));
  C12T28SOI_LR_IVX8_P0 g2823(.A (BACON), .Z (n_26));
  C12T28SOI_LR_NAND2X3_P0 g2820(.A (EA[0]), .B (n_8), .Z (busy));
  C12T28SOI_LR_IVX4_P0 g2824(.A (n_15), .Z (n_23));
  C12T28SOI_LR_IVX8_P0 g2825(.A (n_24), .Z (D100));
  C12T28SOI_LR_NAND2AX7_P0 g2822(.A (EA[0]), .B (n_8), .Z (n_66));
  C12T28SOI_LR_NOR2X7_P0 g2818(.A (EA[0]), .B (n_5), .Z (ATUM));
  C12T28SOI_LR_NOR2X3_P0 g2819(.A (DEV), .B (n_7), .Z (n_20));
  C12T28SOI_LR_NOR2AX6_P0 g2829(.A (n_58), .B (credito[4]), .Z (n_15));
  C12T28SOI_LR_NAND2X7_P0 g2830(.A (n_6), .B (n_53), .Z (n_24));
  C12T28SOI_LR_NOR2X7_P0 g2828(.A (n_6), .B (n_5), .Z (BACON));
  C12T28SOI_LR_NOR3X6_P0 g2821(.A (n_6), .B (n_11), .C (EA[1]), .Z
       (GREEN));
  C12T28SOI_LR_NOR3X6_P0 g2826(.A (R_bacon), .B (DEV), .C (R_atum), .Z
       (n_4));
  C12T28SOI_LR_NOR3X6_P0 g2827(.A (R_green), .B (DEV), .C (R_bacon), .Z
       (n_21));
  C12T28SOI_LR_NOR2X7_P0 g2832(.A (EA[1]), .B (n_11), .Z (n_3));
  C12T28SOI_LR_IVX4_P0 g2831(.A (n_5), .Z (n_2));
  C12T28SOI_LR_NOR2X7_P0 g2836(.A (n_0), .B (EA[2]), .Z (n_8));
  C12T28SOI_LR_OR2X8_P0 g2835(.A (R_green), .B (R_atum), .Z (n_7));
  C12T28SOI_LR_NAND2X7_P0 g2834(.A (EA[2]), .B (EA[1]), .Z (n_5));
  C12T28SOI_LR_NOR2X7_P0 g2833(.A (credito[2]), .B (credito[3]), .Z
       (n_58));
  C12T28SOI_LR_NOR2X7_P0 g2837(.A (EA[2]), .B (EA[1]), .Z (n_53));
  C12T28SOI_LR_IVX8_P0 g2842(.A (credito[2]), .Z (n_1));
  C12T28SOI_LR_IVX8_P0 g2841(.A (credito[3]), .Z (n_44));
  C12T28SOI_LR_IVX8_P0 g2839(.A (EA[2]), .Z (n_11));
  C12T28SOI_LR_IVX4_P0 g2843(.A (reset), .Z (n_76));
  C12T28SOI_LR_IVX8_P0 g2838(.A (EA[1]), .Z (n_0));
  C12T28SOI_LR_IVX8_P0 g2844(.A (credito[1]), .Z (n_9));
  C12T28SOI_LR_IVX8_P0 g2845(.A (EA[0]), .Z (n_6));
  C12T28SOI_LR_IVX8_P0 g2840(.A (credito[0]), .Z (n_33));
endmodule

